security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$DwlGywzr0WB9ziQBoXz6QeIDklJmqxXJ/ZU3bCUl1lBfy4olo0mEW
                        roles: 'ROLE_ADMIN'
                    test:
                        password: $2y$12$1sZXPUAuyLv5PSWigKfjMOtczuaB.nNG7Kou5st6blZ2UB9KBtpy6
                        roles: 'ROLE_ADMIN'
        user_db_provider:
            entity:
                class: App\Entity\User
                property: apiKey

    role_hierarchy:
            ROLE_ADMIN: [ROLE_API]
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic: true
            provider: in_memory
        api: 
            pattern: ^/api/
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            provider: user_db_provider

    access_control:
        - { path: ^/api/, roles: ROLE_API }
        - { path: ^/admin/, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User:
           algorithm: bcrypt
           cost: 12
